version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment below if you want to mount local code for development
    # volumes:
    #   - .:/app
